version: "3"
services:
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command:
            - mongod
    love:
        build: .
        environment:
            - MODE=production
        ports:
            - 6666:6666
        links:
            - mongodb
        depends_on:
            - mongodb
        restart: always
        command:
            - start
